SBS

* Yōgaḥ


** Taittirīyōpaniṣad

The Core Problematic — Bondage and Freedom. The natural state is pervaded by fear: bhīṣāsmāt vātaḥ plavate. It is pervasive, intrinsic to life, especially the social and political life. Freedom is freedom from fear. Yōga is about reaching the fearless state: abhayām pratiṣṭhām vindate.

Fear, and therefore bondage, is intrinsic to the natural state because the cause of fear is also the fundemental dynamic within the natural world: differentiation, most fundementally between an interior and an exterior—self and other, "us" and "them": yadā hy ev aiṣa etasminn udaram antaraṁ kurute, atha tasya bhayaṁ bhavati.

The joyous state, the state of freedom, is rooted in a transformative insight of the unity of the embodied person, in its five layers (material, functional, sensory, cognitive, experiential), and the body of the heavens (?the natural world, or some transendent reality).

It is a state that transcends conventions: kimahaṁ sādhu nākaravam, kim ahaṁ pāpam akaravam iti. Does this mean there is no morality in the state of freedom? (We'll come back to this with the Gīta)

** Līlōpākhyānam

Our social identities are constructed by us and are disrupted by a recontextualization of our social environment. A thought experiment: what changes if we know this is not real? What doesn't change (?morality ?love)?

** Sulabhā Janaka samvādaḥ

** Something on meditation ?

** Milinda Panha

** Vasubandhu on anātma

** Jayanta ātmavāda

** Dharmakīrti on Kṣaṇabhaṇga

** Śāntideva Kṣānti Dhyāna Pāramitē

** Gīta on yoga, karma, dharma

* Dharmaḥ

* Nyāyaḥ
